
trigger:
- master

pool:
  vmImage: ubuntu-latest

strategy:
  matrix:
    chrome:
      browser: chrome
  maxParallel: 2
  
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

  # Starter pipeline
- task: Maven@4
  inputs:
    mavenPomFile: 'RestAssuredAutomationFramework-master/pom.xml'
    goals: 'clean test'
    options: '-Dsurefire.suiteXmlFiles=testng.xml'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false

- script: |
    echo "Running tests..."
    # Your test command that generates Extent Report
  displayName: 'Run Tests'

- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '/TestResults/ExtentReport'
    artifact: 'ExtentReport'
    publishLocation: 'pipeline'


